export { AUTH_ENDPOINTS, BRAND_ENDPOINTS, CATEGORY_ENDPOINTS, SUBCATEGORY_ENDPOINTS, USER_ENDPOINTS, PRODUCT_ENDPOINTS, METRICS_ENDPOINTS, INVENTORY_ENDPOINTS, ORDER_ENDPOINTS, DASHBOARD_ENDPOINTS, SUPPLIER_ENDPOINTS } from './endpoints';


// Add more endpoint modules here as needed
// export { ORDERS_ENDPOINTS } from './orders';
